version: "3.8"

services:
  # 1. PostgreSQL Database
  postgres:
    image: postgres:alpine # أحدث إصدار (Postgres 18)
    container_name: neuromeet-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "##anas4263Anas"
      POSTGRES_DB: neuromeet_db
    ports:
      - "5433:5432"
    volumes:
      # 👇 التعديل هنا: شيلنا /data عشان Postgres 18 بيطلب المسار الرئيسي
      - pgdata:/var/lib/postgresql

  # 2. Redis In-Memory Cache
  redis:
    image: redis:alpine
    container_name: neuromeet-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
