import { Student, StudentGroup } from "../types";

export const dummyStudentGroups: StudentGroup[] = [
  { id: "g1", name: "System Design Cohort", color: "bg-brand-cyan", memberCount: 45 },
  { id: "g2", name: "Web Dev Bootcamp", color: "bg-brand-purple", memberCount: 32 },
  { id: "g3", name: "Advanced Algorithms", color: "bg-status-live", memberCount: 28 },
  { id: "g4", name: "Machine Learning Lab", color: "bg-status-warning", memberCount: 22 },
  { id: "g5", name: "Capstone Projects", color: "bg-primary-light", memberCount: 38 },
];

export const dummyStudents: Student[] = [
  {
    id: "s1",
    name: "Ahmed Hassan",
    email: "ahmed.hassan@nu.edu.eg",
    groups: [
      { name: "System Design Cohort", color: "bg-brand-cyan" },
      { name: "Web Dev Bootcamp", color: "bg-brand-purple" }
    ],
    enrolledDate: "Sep 2025",
    lastActive: "2 hours ago",
    isActive: true,
    totalMeetings: 24,
    avgEngagement: 92,
  },
  {
    id: "s2",
    name: "Mariam Khaled",
    email: "mariam.khaled@nu.edu.eg",
    groups: [{ name: "System Design Cohort", color: "bg-brand-cyan" }],
    enrolledDate: "Sep 2025",
    lastActive: "5 mins ago",
    isActive: true,
    totalMeetings: 22,
    avgEngagement: 88,
  },
  {
    id: "s3",
    name: "Youssef Sameh",
    email: "youssef.sameh@nu.edu.eg",
    groups: [{ name: "Web Dev Bootcamp", color: "bg-brand-purple" }],
    enrolledDate: "Oct 2025",
    lastActive: "1 day ago",
    isActive: false,
    totalMeetings: 18,
    avgEngagement: 75,
  },
  {
    id: "s4",
    name: "Nadine Ashraf",
    email: "nadine.ashraf@nu.edu.eg",
    groups: [
      { name: "Advanced Algorithms", color: "bg-status-live" },
      { name: "Capstone Projects", color: "bg-primary-light" }
    ],
    enrolledDate: "Sep 2025",
    lastActive: "30 mins ago",
    isActive: true,
    totalMeetings: 20,
    avgEngagement: 95,
  },
  {
    id: "s5",
    name: "Omar Tamer",
    email: "omar.tamer@nu.edu.eg",
    groups: [{ name: "Machine Learning Lab", color: "bg-status-warning" }],
    enrolledDate: "Feb 2026",
    lastActive: "3 hours ago",
    isActive: true,
    totalMeetings: 10,
    avgEngagement: 82,
  },
  {
    id: "s6",
    name: "Hana Sherif",
    email: "hana.sherif@nu.edu.eg",
    groups: [{ name: "Capstone Projects", color: "bg-primary-light" }],
    enrolledDate: "Sep 2025",
    lastActive: "Just now",
    isActive: true,
    totalMeetings: 30,
    avgEngagement: 91,
  },
  {
    id: "s7",
    name: "Karim Adel",
    email: "karim.adel@nu.edu.eg",
    groups: [{ name: "Web Dev Bootcamp", color: "bg-brand-purple" }],
    enrolledDate: "Oct 2025",
    lastActive: "2 days ago",
    isActive: false,
    totalMeetings: 14,
    avgEngagement: 68,
  },
  {
    id: "s8",
    name: "Laila Yasser",
    email: "laila.yasser@nu.edu.eg",
    groups: [
      { name: "Advanced Algorithms", color: "bg-status-live" },
      { name: "Machine Learning Lab", color: "bg-status-warning" }
    ],
    enrolledDate: "Sep 2025",
    lastActive: "1 hour ago",
    isActive: true,
    totalMeetings: 26,
    avgEngagement: 97,
  },
  {
    id: "s9",
    name: "Mostafa Ali",
    email: "mostafa.ali@nu.edu.eg",
    groups: [{ name: "Machine Learning Lab", color: "bg-status-warning" }],
    enrolledDate: "Feb 2026",
    lastActive: "5 days ago",
    isActive: false,
    totalMeetings: 8,
    avgEngagement: 71,
  },
  {
    id: "s10",
    name: "Farah Ibrahim",
    email: "farah.ibrahim@nu.edu.eg",
    groups: [{ name: "Capstone Projects", color: "bg-primary-light" }],
    enrolledDate: "Sep 2025",
    lastActive: "15 mins ago",
    isActive: true,
    totalMeetings: 28,
    avgEngagement: 89,
  },
  {
    id: "s11",
    name: "Ali Nour",
    email: "ali.nour@nu.edu.eg",
    groups: [{ name: "System Design Cohort", color: "bg-brand-cyan" }],
    enrolledDate: "Sep 2025",
    lastActive: "4 hours ago",
    isActive: true,
    totalMeetings: 21,
    avgEngagement: 85,
  },
  {
    id: "s12",
    name: "Sara Gamal",
    email: "sara.gamal@nu.edu.eg",
    groups: [{ name: "Web Dev Bootcamp", color: "bg-brand-purple" }],
    enrolledDate: "Oct 2025",
    lastActive: "1 week ago",
    isActive: false,
    totalMeetings: 12,
    avgEngagement: 64,
  },
];