import { Recording } from "../types";
export const dummyRecordings: Recording[] = [
  {
    id: "rec-1",
    title: "System Design Lecture 6 — Microservices & API Gateway",
    course: "System Design & Architecture",
    dateTime: "May 16, 2026 at 11:00 AM",
    duration: 90,
    fileSize: "340 MB",
    viewsCount: 154,
    videoUrl: "/recordings/system-design-6",
    image: "/meeting.webp",
    topics: ["Microservices", "API Gateway", "Event-Driven Architecture"],
  },
  {
    id: "rec-2",
    title: "Algorithms Q&A — Dynamic Programming Patterns",
    course: "Algorithms & Data Structures",
    dateTime: "May 14, 2026 at 02:00 PM",
    duration: 60,
    fileSize: "210 MB",
    viewsCount: 98,
    image: "/meeting.webp",
    videoUrl: "/recordings/algorithms-dp",
    topics: ["Dynamic Programming", "Memoization", "Tabulation"],
  },
  {
    id: "rec-3",
    title: "React Server Components & Streaming SSR",
    course: "Advanced Web Development",
    dateTime: "May 10, 2026 at 03:00 PM",
    duration: 120,
    fileSize: "450 MB",
    viewsCount: 212,
    image: "/meeting.webp",
    videoUrl: "/recordings/rsc-streaming",
    topics: ["Next.js", "Server Components", "Suspense"],
  },
  {
    id: "rec-4",
    title: "Introduction to Neural Networks & Backpropagation",
    course: "Artificial Intelligence & ML",
    dateTime: "May 05, 2026 at 09:30 AM",
    duration: 110,
    fileSize: "410 MB",
    viewsCount: 320,
    image: "/meeting.webp",
    videoUrl: "/recordings/neural-networks",
    topics: ["Neural Networks", "Gradient Descent", "Backpropagation"],
  },
];
