export const AUTH_CONSTANTS = {
  
  ACCESS_TOKEN_EXPIRY: '1h',
  
  REFRESH_TOKEN_EXPIRY: '7d',
  
  REFRESH_TOKEN_MAX_USES: 100,
  
  RESET_TOKEN_EXPIRY_MS: 10 * 60 * 1000,
  
  OTP_EXPIRY_MS: 2 * 60 * 1000,
  
  UNVERIFIED_USER_MAX_AGE_MS: 1 * 60 * 60 * 1000,
  
  OAUTH_HANDOFF_TOKEN_EXPIRY: '1m',
  
  BCRYPT_SALT_ROUNDS: 12,
} as const;
